### ISSUE TITLE
Problem with decimal order size on BTT pair

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#10]
Problem on BTT/USDT pair  (other pair work fine)
I try place order market sell with 166732.37090638 BTT  (its 60$) to USDT with method PlaceMarginOrder

Get error: "Order quantity doesn't conform to the required lot size: 1"
I think its problem with rounding numbers. btt because has 8 digitals after dot 

![image](https://user-images.githubusercontent.com/61819835/105692972-2f24fa00-5f10-11eb-8e32-c332002d1796.png)

**Comment by burakoner** [comment]
You must obey trading rules for product. You can get rules via             
`var products = api.GetProducts();`

**Comment by devopg** [comment]
oh sorry
its bitmax problem, some pair allow place order  in spite of rules (lotSize from GetProducts ) 
but on btt strict rules..... write about problem to bitmax
