### ISSUE TITLE
WS summary channel 

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#12]
Hello how i can subscrib to summary channel ?

from bitmax support: 

> This data can be updated through the summary channel subscription
> {op: "sub", id: "FCuCKYIqjmfhECfw", code: 0, ch: "summary"}

**Comment by burakoner** [comment]
There is no description about summary channel in documentation. But I tried and got response as below. I'll add a SubscribeToSummary method in BitMaxSocketClient class. Give me a few hours.

![Screenshot_13](https://user-images.githubusercontent.com/21169085/107619447-3d8b4980-6c64-11eb-89ce-18ecbec4b575.png)

**Comment by burakoner** [comment]
You can check it out both https://github.com/burakoner/BitMax.Net/commit/bd882f6b65d25a9cbc7340438606de94da76c2be and https://www.nuget.org/packages/BitMax.Net/2.0.2

**Comment by devopg** [comment]
yes this methid need for get last price (with delay) for all pairs.

**Comment by devopg** [comment]
I see problem , in console debug get "unhandled msg" but i set Action for method 

![image](https://user-images.githubusercontent.com/61819835/107685671-4f490d00-6cb5-11eb-92ba-f7d92993beb0.png)

and 
"{op: "sub", id: "FCuCKYIqjmfhECfw", code: 0, ch: "summary"}"  
can be without pass pair and list of pair.  Without set pairs will receive prices for all pairs

**Comment by burakoner** [comment]
Try https://www.nuget.org/packages/BitMax.Net/2.0.3 or https://github.com/burakoner/BitMax.Net/commit/fdabe756e2920c2955934d15ffff34171f77821d

**Comment by devopg** [comment]
thx all work good !!!!
