### ISSUE TITLE
BitMaxCashOrderTimeInForce must have 3 value!!!

### ISSUE THREAD

**Issue by fotrosi** [burakoner/BitMax.Net#14]
Hi,
In place order BitMaxCashOrderTimeInForce enum must have 3 values but have 2 values. FOK (Fill Or Kill) is missing.

**Comment by burakoner** [comment]
Hi. There is no documentation about this feature but I added for you. You can check it out at https://github.com/burakoner/BitMax.Net/commit/cce9e7b302ab658b02afe1e02020310bf437167a or https://www.nuget.org/packages/BitMax.Net/2.1.0
