### ISSUE TITLE
Ascendex.com instead of bitmax.io

### ISSUE THREAD

**Issue by Trumpeta2021** [burakoner/BitMax.Net#15]
Hello,
i try to get my balances, but it looks like program want to call API on **bitmax.io**. Now it is **ascendex.com**.
What is wrong, please?
Thank you

() **HttpRequestException** - Při odesílání požadavku došlo k chybě.
  **WebException** - Vzdálený název nelze rozpoznat: '**bitmax.io**'
     v System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   v System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by Trumpeta2021** [comment]
I got it:

`BitMaxClientOptions options = new BitMaxClientOptions();`
`options.BaseAddress = "https://ascendex.com";`
`BitMaxClient originalAPI = new BitMaxClient(options);`

**Comment by burakoner** [comment]
gratz
