### ISSUE TITLE
NullRef on GetAccountInfo

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#2]
Today start throw exception on connection.
Repeat: My IP is changed and bitmax api key dont allow my new IP. (I think is this problem)
![image](https://user-images.githubusercontent.com/61819835/104292088-6e455b00-54cd-11eb-9e02-8e407edc67d8.png)

**Comment by burakoner** [comment]
Yes you're right. But Api wrapper must consider all possibilities. I fixed it in https://github.com/burakoner/BitMax.Net/commit/055b63fddc774a6f9cfedfe970c3115646297a77. Both on github and nuget.

Have a nice day
