### ISSUE TITLE
GetCandles unlimited freez some time

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#3]
Method: GetCandles
Some time unlimited freez(await) on method GetCandles
![image](https://user-images.githubusercontent.com/61819835/104315245-b8d5d000-54eb-11eb-9cef-f92b1625c8e1.png)

**Comment by burakoner** [comment]
Can you specify whic pair, which internal etc. I need to make test to ensure

**Comment by burakoner** [comment]
The code below finished in 28 seconds in debug mode with no errors.

var bmc = new BitMaxClient();
for(var i = 1; i <= 100; i++)
{
      Console.Write($"Getting {i}");
      var bmc_c = bmc.GetCandles("BTC/USDT", BitMaxPeriod.OneHour, 10);
      Console.WriteLine($" Done");
}

**Comment by devopg** [comment]
I get freez 2 times during 2 days.
i think because httpclient havent timeout?!
Maybe should add global timeout setting ? 

```
var bitmaxClient = new BitmaxClient(key, secret);
bitmaxClient.SetHttpTimeout(TimeSpan.FromMinute(1));

```

**Comment by burakoner** [comment]
As you can see in CryptoExchange https://github.com/JKorf/CryptoExchange.Net/blob/3b6463015aec589e80e0758eaf1d0823f5f6af62/CryptoExchange.Net/Objects/Options.cs there is already timeout option. Default value is 30 seconds. You can set as below

![Screenshot_1](https://user-images.githubusercontent.com/21169085/104424626-acf01980-5590-11eb-8849-e6b96c1d16c5.png)

But I want to repeat. There is a default 30 seconds timeout in codes. It should work even you dont specify.

**Comment by devopg** [comment]
if default is set to 30 second  then this is not the problem with timeout

 I'll watch a couple of days )
