### ISSUE TITLE
Wrong enum status  BitMaxCashOrderStatus

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#4]
BitMaxCashOrderStatus:Cancelled
should be : 
BitMaxCashOrderStatus:Canceled

![image](https://user-images.githubusercontent.com/61819835/104581794-1c890600-5670-11eb-83da-fc3f2b99b08a.png)

**Comment by burakoner** [comment]
AS you can see in api documentation(https://bitmax-exchange.github.io/bitmax-pro-api/#place-order) its name is "Cancelled". I got same response with api docs. But unfortunatelly I need to say, BitMax Api has multiple structures and enums. There may be different definitions. So I added a second enum string for Canceled in https://github.com/burakoner/BitMax.Net/commit/102b4010227ff5802728ced90689dfb1eef89f6c commit. Have a nice day
