### ISSUE TITLE
WS Login return lie result information 

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#5]
Login method return success: false without info but next subsribe method fine work

```
var credentials = new ApiCredentials(key, secret);
 _ws = new BitMaxSocketClient(new BitMaxSocketClientOptions(account_info.Data.AccountGroup) {ApiCredentials = credentials});
 var auth = _ws.Login();
 _ws.SubscribeToMarginBalanceAndOrders(....)  // <-- work good 
```
![image](https://user-images.githubusercontent.com/61819835/104582320-c8325600-5670-11eb-8fcc-8ef784c93b25.png)

**Comment by burakoner** [comment]
There is a problem with CryptoExchange QueryAndWait, SubscribeAndWait methods. They assume that the first response of websocket after a request, belongs to query request. In other words. While you are getting some data (Lets say R1 to this),  if you request a second data (for example a subscription or login, R2), QueryAndWait methods assumes R1 response as R2. Unfortunatelly the first response may be welcome message as well. I think this a serious problem and I am talking to JKorf. You need to check updatesucsription until we solve it.

**Comment by devopg** [comment]
hm today subscibe to orders stream dont work 
I try run 1) clear sanbox 2) place limit order and cancel in browser 
Error and exceptions missing but in console nothing too

 ```
 static async Task Main(string[] args)
        {
            var cultureInfo = new CultureInfo("en-US");
            CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
            
            var key = "key";
            var secret = "sec";
            var group = 7;
            var credentials = new CryptoExchange.Net.Authentication.ApiCredentials(key, secret);
            var ws = new BitMaxSocketClient(new BitMaxSocketClientOptions(group) { ApiCredentials = credentials });

            await ws.UnsubscribeAll();
            var auth = ws.Login();

            var sub05 = ws.SubscribeToMarginBalanceAndOrders((data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"Balance >> {data.Asset} AB:{data.AvailableBalance} TB:{data.TotalBalance}");
                }
            }, (data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"Order >> {data.Symbol} OT:{data.OrderType} P:{data.Price} SP:{data.StopPrice}");
                }
            });
            Console.ReadKey();
}
```

PS. and in this code i get unsuccess login to 
![image](https://user-images.githubusercontent.com/61819835/104588141-02075a80-5679-11eb-9204-2feed6099576.png)

**Comment by burakoner** [comment]
I've fixed this issue in commit https://github.com/burakoner/BitMax.Net/commit/368953cc36edb841044f10afdc3024ef8bbf7eb8. I also created a new ctor option in BitMaxSocketClientOptions. You can use as 
`new BitMaxSocketClientOptions(accountGroup, credentials)`

Have a nice day

**Comment by devopg** [comment]
![image](https://user-images.githubusercontent.com/61819835/104713466-f7aa9680-5734-11eb-9afe-98265f270c46.png)
yes now work.
