### ISSUE TITLE
SubscribeToMarginBalanceAndOrders WS dont work

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#6]
hm today subscibe to orders stream dont work 
I try run 1) clear sanbox 2) place limit order and cancel in browser 
Error and exceptions missing but in console nothing too.

SubscribeToCandles is working. I think its problem with methods wich need auth.

 ```
 static async Task Main(string[] args)
        {
            var cultureInfo = new CultureInfo("en-US");
            CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
            
            var key = "key";
            var secret = "sec";
            var group = 7;
            var credentials = new CryptoExchange.Net.Authentication.ApiCredentials(key, secret);
            var ws = new BitMaxSocketClient(new BitMaxSocketClientOptions(group) { ApiCredentials = credentials });

            await ws.UnsubscribeAll();
            var auth = ws.Login();

            var sub05 = ws.SubscribeToMarginBalanceAndOrders((data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"Balance >> {data.Asset} AB:{data.AvailableBalance} TB:{data.TotalBalance}");
                }
            }, (data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"Order >> {data.Symbol} OT:{data.OrderType} P:{data.Price} SP:{data.StopPrice}");
                }
            });
            Console.ReadKey();
}
```

PS. and in this code i get unsuccess login to 
![image](https://user-images.githubusercontent.com/61819835/104588141-02075a80-5679-11eb-9204-2feed6099576.png)

_Originally posted by @devopg in https://github.com/burakoner/BitMax.Net/issues/5#issuecomment-760141421_

**Comment by burakoner** [comment]
Are you sure that your account group is 7?

**Comment by devopg** [comment]
yes. 
![image](https://user-images.githubusercontent.com/61819835/104630973-9939d580-56ac-11eb-9e1c-7c11d58b0dd2.png)

**Comment by burakoner** [comment]
As you can see in the pictures below, both balance and order updates are working. Please review your codes.

![Screenshot_1](https://user-images.githubusercontent.com/21169085/104699638-1bb1ac00-5724-11eb-810a-fcdf06986087.png)

![Screenshot_2](https://user-images.githubusercontent.com/21169085/104699641-1ce2d900-5724-11eb-932b-d795c30d506e.png)

**Comment by devopg** [comment]
Hi. you use spot sub, i say about margin sub 
SubscribeTo**MarginBalanceAndOrders**
Then balances change is work , but then open / close limit orders - console empty .


![image](https://user-images.githubusercontent.com/61819835/104714245-0b0a3180-5736-11eb-9946-908cd6e1fc9c.png)
balance change work , order dont show

**Comment by burakoner** [comment]
Try now with https://github.com/burakoner/BitMax.Net/commit/4cd5c0b410a8f06ff90cb712bb673648fa2e2494 or https://www.nuget.org/packages/BitMax.Net/1.3.2

**Comment by devopg** [comment]
NOW WORK!
