### ISSUE TITLE
ThreadSafe Information WS

### ISSUE THREAD

**Issue by devopg** [burakoner/BitMax.Net#9]
I create ASp.net project.
Any call asp.net action is new thread.

1) BitMaxSocketClient  is thread save ? 
1.1) Should i create like singletone ?  

2) can i call many times method 'Login' per one object ? or its create many connections ? 
3) should i check that i already subscribe ?
3.1) what is happing if i call same time for one part ? 

```
            if(! I_ALREAD_SUBCRIBE_TO_BTC_USDT){

            var sub04 = ws.SubscribeToCandles(new List<string> { "BTC/USDT", }, BitMaxPeriod.OneHour, (data) =>
            {
                if (data != null)
                {
                    Console.WriteLine($"111Candle {Thread.CurrentThread.ManagedThreadId} >> {data.Symbol} P:{data.Period} OT:{data.OpenTime} O:{data.Open} H:{data.High} L:{data.Low} C:{data.Close} V:{data.Volume}");
                }
            });

            }
```

**Comment by burakoner** [comment]
I'll answer shortly. But if you need more information please don't hesitate

1. Yes
2. No. Bitmax websocket doesnt allow for this.
3. You can use multiple websockets(different BitMaxSocketClient objects) at the same time. It's no problem. You can subscribe same updates from different objects. You can send subscribe method twice in the same client. This doesnt cause any problem.

If you are planning to manage different users data in the same time, You can use a master client for public data, and different other clients for each user

**Comment by devopg** [comment]
thx.
Maybe need add this information to main page

**Comment by burakoner** [comment]
I'll
